# Set your GCP project ID and the zone where you want to create 
# the Kubeflow deployment:
export PROJECT=guille-default
export ZONE=us-central1
export BASE_DIR=${PWD}
export KF_DIR=${BASE_DIR}/k8s/kubeflow
export CONFIG_URI=https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.2.yaml
export CONFIG_FILE=${KF_DIR}/kfctl_k8s_istio.v1.0.2.yaml
export TF_VARS=

#######################
# Pre Requisites
# @todo: automate gcloud cli setup
# @todo: would be nice to move this logic to a Jenkins pipeline orchestrated with k8s + Helm
#######################

deps-macos:
# Download the kfctl v1.0.2 release from the kfctl releases page.
	mkdir utils
	wget -c https://github.com/kubeflow/kfctl/releases/download/v1.0.2/kfctl_v1.0.2-0-ga476281_darwin.tar.gz -O - | tar -xz -C ./utils/

deps-linux:
# Download the kfctl v1.0.2 release from the kfctl releases page.
	mkdir utils
	curl https://github.com/kubeflow/kfctl/releases/download/v1.0.2/kfctl_v1.0.2-0-ga476281_linux.tar.gz -O - | tar -xz -C ./utils/

#######################
# Helpers
#######################

# A helper command to authorize your gcloud cli, used by kfctl and terraform
auth-gcloud:
# authorize gcloud 
	gcloud auth application-default login

#######################
# GCP / GKE
#######################

deploy-google-gke-cluster:
# install any missing terraform plugin
	terraform init
# update the infrastructure if needed
	terraform apply -parallelism=100

destroy-google-gke-cluster:
	terraform destroy -parallelism=100

############
# Kubeflow
######

# Generates Kubeflow infrastructure as code in yaml format
kubeflow-generate-yaml:
# Ensure gcloud has the correct project and compute/zone.
	gcloud config set project ${PROJECT}    
	gcloud config set compute/zone ${ZONE}
# Create the folder to store artifacts generated by kubectl
	mkdir -p ${KF_DIR}/src
	cd ${KF_DIR}/src
# Declare every component of the infra in yaml format
	${BASE_DIR}/utils/kfctl build -V -f ${CONFIG_URI}

kubeflow-deploy:
# deploy the generated infrastructure
	${BASE_DIR}/utils/kfctl apply -V -f ${CONFIG_FILE}

kubeflow-uninstall:
	${BASE_DIR}/utils/kfctl delete -V -f ${CONFIG_FILE}


all: deploy-google-gke-cluster kubeflow-generate-yaml kubeflow-deploy
